### {line_length: 128}
add_custom_command(
    COMMAND
    ${CMAKE_COMMAND}
    -E
    env
    OUTPUT_DIRECTORY="${CMAKE_CURRENT_BINARY_DIR}"
    WARN_AS_ERROR="${DOXYGEN_WARN_AS_ERROR}"
    CLANG_ASSISTED_PARSING="${DOXYGEN_CLANG_ASSISTED_PARSING}"
    CLANG_OPTIONS="${DOXYGEN_CLANG_OPTIONS}"
    CLANG_DATABASE_PATH="${CMAKE_CURRENT_BINARY_DIR}"
    ${DOXYGEN_EXECUTABLE}
    COMMAND
    cmake
    -E
    touch
    "${DOXYGEN_STAMP_FILE}"
    DEPENDS
    ${DOC_INPUT_FILES}
    OUTPUT
    ${DOXYGEN_STAMP_FILE}
    WORKING_DIRECTORY
    ${CMAKE_CURRENT_SOURCE_DIR}
    COMMENT
    "Generating documentation with Doxygen"
)
