ctest_coverage(BUILD FOO APPEND LABELS BAR RETURN_VALUE FOO)

ctest_coverage(BUILD FOO APPEND LABELS BAR RETURN_VALUE FOO CAPTURE_CMAKE_ERROR BAR QUIET)

ctest_coverage(BUILD FOO APPEND LABELS FOO BAR BAZ RETURN_VALUE FOO CAPTURE_CMAKE_ERROR BAR QUIET)

ctest_coverage(BUILD long_arg____________________________________________________________ APPEND LABELS long_arg____________________________________________________________ RETURN_VALUE long_arg____________________________________________________________)

ctest_coverage(BUILD long_arg____________________________________________________________ APPEND LABELS long_arg____________________________________________________________ RETURN_VALUE long_arg____________________________________________________________ CAPTURE_CMAKE_ERROR long_arg____________________________________________________________ QUIET)

ctest_coverage(BUILD long_arg____________________________________________________________ APPEND LABELS long_arg____________________________________________________________ long_arg____________________________________________________________ long_arg____________________________________________________________ RETURN_VALUE long_arg____________________________________________________________ CAPTURE_CMAKE_ERROR long_arg____________________________________________________________ QUIET)