function(FOO)
endfunction()

function(FOO)
endfunction(FOO)

function(FOO arg1)
endfunction()

function(FOO arg1)
endfunction(FOO)

function(FOO long_argument__________________________________________________________)
endfunction()

function(LONG_FUNCTION_NAME____________________________________________________________)
endfunction()

function(LONG_FUNCTION_NAME____________________________________________________________)
endfunction(LONG_FUNCTION_NAME____________________________________________________________)

function(LONG_FUNCTION_NAME____________________________________________________________ long_argument_________________________________)
endfunction()

function(FOO arg1 arg2 arg3 arg4 long_argument______________________________________)
endfunction()

if(TRUE)
function(FOO arg1)
endfunction()

function(LONG_FUNCTION_NAME____________________________________________________________)
endfunction(LONG_FUNCTION_NAME____________________________________________________________)

function(FOO arg1 arg2 arg3 arg4 long_argument______________________________________)
endfunction()
endif()