set(MY_VAR -DCMAKE_INSTALL_PREFIX="\"${INSTALL_PREFIX}\"")

set(MY_VAR -DCMAKE_INSTALL_PREFIX="\"${INSTALL_PREFIX}\"")

set(MY_VAR -DCMAKE_INSTALL_PREFIX="\"${INSTALL_PREFIX}\"" FOO)

set(MY_VAR -DCMAKE_INSTALL_PREFIX="\"${INSTALL_PREFIX}\"" FOO)

set(MY_VAR
    -DCMAKE_INSTALL_PREFIX="\"${INSTALL_PREFIX}\""
    FOO
    -DCMAKE_INSTALL_PREFIX="\"${INSTALL_PREFIX}\""
)

set(MY_VAR
    -DCMAKE_INSTALL_PREFIX="\"${INSTALL_PREFIX}\""
    FOO
    -DCMAKE_INSTALL_PREFIX="\"${INSTALL_PREFIX}\""
)

set(MY_VAR
    -DCMAKE_INSTALL_PREFIX="\"${INSTALL_PREFIX}\""
    FOO
    -DCMAKE_INSTALL_PREFIX="\"${INSTALL_PREFIX}\""
    foo
)

set(MY_VAR
    -DCMAKE_INSTALL_PREFIX="\"${INSTALL_PREFIX}\""
    FOO
    -DCMAKE_INSTALL_PREFIX="\"${INSTALL_PREFIX}\""
    foo
)
